### ISSUE TITLE
[ADD] 프로젝트 기초 세팅

### ISSUE THREAD

**Issue by skylartosf** [TeamHARA/KAERA_Android#1]
## ✅ **To-do List**

- [x] main에서 develop 브랜치 파기
- [x] theme 설정 (not include font padding 등)
- [x] color 설정
- [x] font 설정
- [x] string 설정
- [x] .gitignore 설정
- [x] build.gradle에 라이브러리 의존성 추가(implementation)
- [x] application 설정 - timber
- [x] local properties 설정
- [x] #2
- [x] extension 만들기 (유틸함수 등)

**Comment by IslandofDream** [comment]
CI CD는 yaml 파일 쓰는거 같아서 분리했음!

**Comment by IslandofDream** [comment]
라이브러리 의존성도 초반에 너무 많이 추가하면 빌드가 느려져서 차차 필요할따마다 추가하는 것으로 하겠습니다!
