### ISSUE TITLE
[FIX] 고민 보석함 삭제 이슈 해결

### ISSUE THREAD

**Issue by wkdyujin** [TeamHARA/KAERA_Android#102]
## 🗣️ **Issue**

보관함에서 고민 삭제 후 되돌아올 때 바로 반영되지 않는 이슈 해결하겠습니다

## ✅ **To-do List**

- [x] 삭제 이슈 해결
- [x] 고민 템플릿 UI 수정(현재 hasUsed 반영 X)
- [x] 인스타공유 UI 수정(캐라 인스타 페이지 이동)
- [x] 온보딩 UI 수정
