### ISSUE TITLE
[FIX] 홈화면 리싸이클러뷰 관련 QA 반영

### ISSUE THREAD

**Issue by IslandofDream** [TeamHARA/KAERA_Android#107]
## 🗣️ **Issue**

홈화면에서 리싸이클러뷰 관련해서 발생하는 QA들을 처리할 예정입니다.

## ✅ **To-do List**

- [x] 홈화면 원석 및 보석 배치
- [x] 없는 아이템 클릭시 상세화면으로 넘어가는 문제
- [ ] 리싸이클러뷰 하단 마진 문제
