### ISSUE TITLE
[FIX] 작성화면 상단 guideline 수정 및 setOnSinglistener , 터치타겟 확대, 리플효과 추가

### ISSUE THREAD

**Issue by IslandofDream** [TeamHARA/KAERA_Android#111]
## 🗣️ **Issue**
고민 템플릿 '작성하러 가기' 버튼 관련 QA 작업하려고 합니다.

## ✅ **To-do List**

- [x] 서버통신 관련 setonSingleListener 로직 적용 
- [x] 터치타겟 수정
- [x] 리플 효과 추가
- [x] 상단 guideline 관련
