### ISSUE TITLE
[FEAT] 고민캐기 이후 명언 다이얼로그 출력

### ISSUE THREAD

**Issue by IslandofDream** [TeamHARA/KAERA_Android#112]
## 🗣️ **Issue**

고민캐기 이후 명언다이얼로그가 나와야 하므로 그부분 수정하려고 합니다.

## ✅ **To-do List**

- [x] 명언다이얼로그 뷰 수정
- [x] 서버통신 성공 이후 명언다이얼로그 출력
- [x] 원석 12개 일시 다이얼로그 출력
- [x] 상단 보석이펙트 잘림 수정
- [x] 명언캐기 이후 플로우 수정
