### ISSUE TITLE
[FEAT] 릴리즈 용 키스토어 생성 및 키스토어 관리

### ISSUE THREAD

**Issue by IslandofDream** [TeamHARA/KAERA_Android#120]
## 🗣️ **Issue**

릴리즈를 위해서 키스토어 생성 및 관리 파일을 만드려고합니다. 
## ✅ **To-do List**

- [x] KeyStore 생성
- [x] KeyStore.properties 생성
- [ ] 카카오 sdk 등록
- [x] 오픈소스 페이지 릴리즈 버전 빌드 테스트
- [ ] 인앱 업데이트 기능 추가
