### ISSUE TITLE
[FIX] 알림 권한 오류 / 해결후 상세화면 오류 수정

### ISSUE THREAD

**Issue by IslandofDream** [TeamHARA/KAERA_Android#130]
## 🗣️ **Issue**

알림활성화 로직이 메인에서 계속 불리는 현상을 수정하려고 합니다. 
더불어서 해결 후 상세화면에서 백그라운드로 나갈시 에딧텍스트가 초기화 되는 현상을 수정하려고합니다.

## ✅ **To-do List**

- [x] 알림활성화 로직 수정
- [x] 백그라운드 / 포어그라운드 전환시 버그 수정
- [x] 문구 오타 수정
- [x] 홈 프래그먼트 페이지 고정 수정
