### ISSUE TITLE
[UI/FEAT] 고민작성 템플릿 화면

### ISSUE THREAD

**Issue by IslandofDream** [TeamHARA/KAERA_Android#18]
## 🗣️ **Issue**

![image](https://github.com/TeamHARA/KAERA_Android/assets/70648111/730659c4-4395-4f30-a9cb-a3ea5aac60cf) ![image](https://github.com/TeamHARA/KAERA_Android/assets/70648111/26abe5ef-a86d-4cdd-b126-36dc79d9edc3)

고민 작성 화면에서 템플릿 선택 후의 UI를 짜두려고 합니다. Visibility 조절로 할지는 조금 생각해보려고 합니다.

## ✅ **To-do List**

- [x]  템플릿 UI 구성
- [x]  템플릿 선택후 화면 교체 로직
- [ ] 글자수 및 완료버튼 활성화 로직
- [x] 스크롤 조절 로직

- ~~EditText 포커스 로직 <- 후순위 구현~~
