### ISSUE TITLE
[FEAT/UI] 고민작성 디자인 변경 / UX 요소 추가

### ISSUE THREAD

**Issue by IslandofDream** [TeamHARA/KAERA_Android#29]
## ✅ **To-do List**
- 고민작성 UI 변경사항을 바꾸고자 합니다.
- 7/30날 회의에서 확정되었던 세부사항들을 반영하고자 합니다. 

- [x]  고민작성 액티비티 디자인 변경
- [x] 템플릿 선택 바텀시트 높이로직 및 선택 후 dismiss 로직 추가
- [x] 고민작성 글자수 제한 추가
- [x] 고민작성 공백 제한
- [x] 조건에 따라서 스낵바 띄우기
- [x] ThanksTo 텍스트 연동
