### ISSUE TITLE
[FEAT] 고민작성 액티비티 서버통신 및 비지니스 로직 적용

### ISSUE THREAD

**Issue by IslandofDream** [TeamHARA/KAERA_Android#37]
## 🗣️ **Issue**

고민작성 부분 서버통신 및 비지니스로직 적용할 예정입니다.

## ✅ **To-do List**

- [x] 템플릿 종류 조회 API연결
- [x] 템플릿 상세조회 API연결
- [x] 템플릿 종류에 따른 화면 변경 구현
- [x] 로딩뷰
- [ ] 커스텀 스낵바 적용
- 미정 : StateFlow 빌더 코드 수정
