### ISSUE TITLE
[FEAT] 보관함 서버 통신 및 비즈니스 로직 적용

### ISSUE THREAD

**Issue by wkdyujin** [TeamHARA/KAERA_Android#39]
## 🗣️ **Issue**

보관함 서버 통신 및 비즈니스 로직 적용

## ✅ **To-do List**

- [x] 템플릿 별 고민글 목록 API 연결
- [x] 템플릿 종류 조회 API 연결
- [x] 서버 통신 결과에 따른  UI 구현
