### ISSUE TITLE
[FEAT] 고민작성 완료 및 고민캐기 다이얼로그변경

### ISSUE THREAD

**Issue by IslandofDream** [TeamHARA/KAERA_Android#41]
## 🗣️ **Issue**

- 8/13 회의때 나온 사항 및 브랜치 머치 후 반영되어야 할 부분들에 대해서 반영하고자 합니다.
## ✅ **To-do List**

- [x] 고민작성 완료 제목 입력칸 초기에 안보이도록 처리
- [x] FreeNote 네이밍 및 데이터바인딩 변경
- [x] 머지 후 미사용 파일 삭제
- [x] 커스텀 스낵바 적용
- [x] 완료 후 날짜선택 다이얼로그 띄우기
- [x] 고민캐기 다이얼로그 변경사항 반영
