### ISSUE TITLE
[REFACTOR] 홈화면 UI 리팩토링

### ISSUE THREAD

**Issue by skylartosf** [TeamHARA/KAERA_Android#49]
## ✅ **To-do List**
![image](https://github.com/TeamHARA/KAERA_Android/assets/66207354/b582fcee-e01f-4819-a528-92c6f4164d20)

- [x] fragment 2개 만들기 (원석/보석 탭, 딱 보석 12개 있는 부분만)
- [x] 각 fragment 안에 = RecyclerView
- [x] ViewPager2로 스와이프 화면 구성
- [x] empty view
