### ISSUE TITLE
[FEAT] 고민 해결 상세 페이지 UI 및 비즈니스 로직

### ISSUE THREAD

**Issue by wkdyujin** [TeamHARA/KAERA_Android#50]
## 🗣️ **Issue**

고민 해결 후 상세페이지 UI를 및 비즈니스 로직을 구성합니다.

## ✅ **To-do List**

- [x] 고민 해결 전 상세페이지 참고하여 해결 후 상세페이지 UI 작성
- [x] 고민 상세 조회 비즈니스 로직
- [x] 고민 상세 조회 API 연결
