### ISSUE TITLE
[Refactor] 고민작성 액티비티 버그 및 사용성 개선

### ISSUE THREAD

**Issue by IslandofDream** [TeamHARA/KAERA_Android#53]
## ✅ **To-do List**

- [x] 앱 백그라운드 진입시 데이터 보존
- [x] 다이얼로그 팝업 방식 수정 -> 애니메이션 적용으로 해결
- [x] 기록저장 경고 다이얼로그 로직 조건 수정
- [x] EditText 폰트 수정
- [x] 변경된 디자인버전으로 디자인 수정
