### ISSUE TITLE
[FEAT] 토큰 재발급 / 토큰상태에 따른 분기처리

### ISSUE THREAD

**Issue by IslandofDream** [TeamHARA/KAERA_Android#68]
## 🗣️ **Issue**

토큰 재발급 및 토큰 상태(토큰이 비어있는가 만료되었는가 등등)에 따른 자동로그인 및 분기처리를 해주고자 합니다.
## ✅ **To-do List**

- [x] 토큰상태 세분화 및 정의
- [x] 토큰 재발급 api 
- [x] 토큰 api및 상태에 따른 분기처리
