### ISSUE TITLE
[FEAT] 마이페이지 연동

### ISSUE THREAD

**Issue by IslandofDream** [TeamHARA/KAERA_Android#74]
## 🗣️ **Issue**

로그인 과정에서 마이페이지에 보여질 이름도 저장하려고 합니다.

## ✅ **To-do List**

- [x] 데이터스토어 이름 + 아이디 저장 로직 추가
- [x] 마이페이지 회원가입 / 회원탈퇴
- [ ] 푸쉬알림 권한 토글 연동 
- [x] 스플래시 애니메이션 및 화면전환 애니메이션
