### ISSUE TITLE
[FEAT] 글 작성/수정/삭제, 데드라인 수정 flow 변경

### ISSUE THREAD

**Issue by skylartosf** [TeamHARA/KAERA_Android#75]
## ✅ **To-do List**

- [x]  글 수정하기 API
- [x]  데드라인 수정하기 API
- [x] 삭제하기 API
- [x] 글수정하기 api 수정
- [x] 남은 기한 수정하기 api → 스낵바 올라오는 타이밍 수정
- [x] 고민 보석 캐기 api
- [x] free flow 글 등록 안 됨
- [ ] DetailBeforeViewModel 전반적으로 : flow collect 할 때 if (it is UiState<Success> 추가 해야 할 듯)
- [x] FragmentHomeJewel : 최신 12개 보여주기
