### ISSUE TITLE
[Chore] 플로우 점검

### ISSUE THREAD

**Issue by IslandofDream** [TeamHARA/KAERA_Android#83]
## 🗣️ **Issue**

플로우 스토리보드 보면서 빠진 부분들 보완하려고 합니다.

## ✅ **To-do List**

- [x] 원석 가득찬 경우 다이얼로그
- [x] 에러 뷰 생성
- [x] 에러뷰 로직
- [x] 로티파일 추가 및 로티 적용
- [x] 앱 런처 아이콘 변경
- [x] 뒤로가기 관련 사용성(ex 홈화면)
- [x] 앱 시작시 네트워크 유무 판단
- [x] 기타 화면연결
