### ISSUE TITLE
[FIX] 고민 템플릿 화면 QA 이슈 해결

### ISSUE THREAD

**Issue by wkdyujin** [TeamHARA/KAERA_Android#88]
## 🗣️ **Issue**

고민템플릿 화면 이슈 해결하겠습니다.

## ✅ **To-do List**

- [x] 터치 타겟 확장(버튼 -> 템플릿 레이아웃 전체)
- [x] figma에 맞추어 item 간 margin 수정
- [x] 보석 이미지 변경
- [x] 스크롤 범위 수정(인스타 공유 배너까지 스크롤)
- [x] 작성하기 기능(액티비티 이동) 구현
