### ISSUE TITLE
[FIX] 마이페이지 및 고민작성 완료버튼 QA 반영

### ISSUE THREAD

**Issue by IslandofDream** [TeamHARA/KAERA_Android#89]
## 🗣️ **Issue**

마이페이지랑 네트워크 에러 처리 부분 QA 반영하려고 합니다.

## ✅ **To-do List**

- [x] 홈화면 로고 이미지 교체  
- [x] 템플릿 질문 조회 API 수정
- [x] 회원탈퇴하기 API 수정
- [x] 스낵바 색상 및 위치 변경하도록 수정
- [x] 고민작성시 뒤로가기 발생할때 경고다이얼로그 로직 적용
