### ISSUE TITLE
[FIX] 홈화면 QA

### ISSUE THREAD

**Issue by wkdyujin** [TeamHARA/KAERA_Android#93]
## 🗣️ **Issue**

홈화면 QA 작업

## ✅ **To-do List**

- [x]  홈화면 페이지네이션 반영된 API로 수정
- [ ] (보류) 고민 12개 존재 시 추가 불가 다이얼로그
- [ ] (보류) 리사이클러뷰 영역 마진 -> 패딩수정(?)
