### ISSUE TITLE
[FIX] 보관함, 글 상세(보석) QA

### ISSUE THREAD

**Issue by wkdyujin** [TeamHARA/KAERA_Android#95]
## 🗣️ **Issue**

보관함과 글 상세(보석) 뷰의 QA 이슈 수정하겠습니다

## ✅ **To-do List**

- [x] 보관함 날짜 포맷 변경
- [x] 보관함 폰트 수정(UI)
- [x] 글 상세(보석) 고민 기간 글자 제거, 리뷰 터치 영역 확대(UI)
- [x] 글 상세(보석) 리뷰 작성 중 터치 영역 변경 시 키보드 제거
